<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-08-04 15:50
=======
# Generated by Django 5.0.7 on 2024-08-04 06:44
>>>>>>> 1ecb008f78279aebdf3b19b2d00c3b073d0ccfe6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_description_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Vacancy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
<<<<<<< HEAD
            field=models.IntegerField(default=0),
=======
            field=models.IntegerField(default=1),
>>>>>>> 1ecb008f78279aebdf3b19b2d00c3b073d0ccfe6
        ),
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
